[package]
name = "americano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
google-calendar = "0.5.0"
serde = "1.0.164"
tokio = { version = "1.28.2", features = ["full"] }
toml = "0.7.5"
